services:
  mediamtx:
    image: oxymoron0/mediamtx:nvidia-ffmpeg
    container_name: mediamtx
    restart: always
    ports:
      - "8554:8554"
    volumes:
      - ./mediamtx_custom.yml:/mediamtx.yml
      - ./ffmpeg/:/ffmpeg/
      - ../sources/:/sources/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]